<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\Events\" />
    <Folder Include="MotionController\LeadShine\" />
    <Folder Include="MotionController\Googol\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y /e &quot;$(ProjectDir)MotionController\ZMotion\Dll&quot; &quot;$(TargetDir)&quot;" />
  </Target>

</Project>
